# fly.toml app configuration file generated for wandiweather on 2025-12-26T16:27:20+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wandiweather'
primary_region = 'syd'

[build]

[env]
  TZ = 'Australia/Melbourne'

[[mounts]]
  source = 'wandiweather_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
